# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dk7CazU8gO6fvtmdwAoIGEg1iilNlJES
"""
import gestion_personas

def verificar_credenciales(login, clave):
    with open("login.txt", "r") as file_login:
        login_correcto = file_login.read().strip()

    with open("clave.txt", "r") as file_clave:
        clave_correcta = file_clave.read().strip()

    if login == login_correcto and clave == clave_correcta:
        return True
    else:
        return False

def mostrar_menu():
    print("Menú de opciones:")
    print("1. Listar personas")
    print("2. Agregar personas")
    print("3. Salir")
    
def agregar():
    print("-- Agregar Datos a un Archivo --")
    archivo = input("Archivo: ")
    contenido = input("Contenido: ")
    gestion_personas.agregar_personas(archivo, contenido)
    
def listar():
    print("-- Mostrar contenido de un archivo -- \n")

    personas_dni = gestion_personas.listar_personasDNI()
    personas_nom = gestion_personas.listar_personasNOM()
    personas_ape = gestion_personas.listar_personasAPE()

    max_length = max(len(personas_dni), len(personas_nom), len(personas_ape))

    for i in range(max_length):
        dni = personas_dni[i] if i < len(personas_dni) else ""
        nom = personas_nom[i] if i < len(personas_nom) else ""
        ape = personas_ape[i] if i < len(personas_ape) else ""
        print(f"{dni}\t{nom}\t{ape}")


    

def salir():
    print("Gracias por su visita....")

def error():
    print("Opción incorrecta")


def main():
    intentos = 0
    while intentos < 2:
        login = input("Ingrese su login: ")
        clave = input("Ingrese su clave: ")

        if verificar_credenciales(login, clave):
            print("Bienvenido al sistema.")
            opcion = 1
            while opcion!=3:
                mostrar_menu()
                opcion = int(input("opcion: "))
                if opcion == 1:
                    listar()
                elif opcion == 2:
                    agregar()
                elif opcion == 3:
                    salir()
                else:
                    error()
            break
        else:
            intentos += 1
            print("Credenciales incorrectas. Por favor, inténtelo de nuevo.")

    if intentos == 2:
        print("Demasiados intentos fallidos. El programa terminará.")
           
main()